### ISSUE TITLE
Advanced Channel Rules won't work

### ISSUE THREAD

**Issue by proedie** [PseudoTV/PseudoTV_Live#14]
Hello.

I have set up a channel based on a playlist and added some advanced channel rules to it. The rules are not obeyed and do not show up when I go back to the rule editor.

However, they DO show up in the settings2.xml file.

Cheers!

**Comment by Lunatixz** [comment]
Thanks for letting me know, This is v.0.8.x (older development) source code and does not reflect the current state of code for the new release. v.0.9.x ... If you are still having issues after v.0.9.x release let me know. THX
