### ISSUE TITLE
What's the preferred method for development conversations?

### ISSUE THREAD

**Issue by Lunatixz** [PseudoTV/PseudoTV_Live#2]
irc
group google hangout
private forum
github

**Comment by learningit** [comment]
They're all ok for me

**Comment by rafaelvieiras** [comment]
Google Group :smile:

**Comment by robnewton** [comment]
Any works

**Comment by Lunatixz** [comment]
Cool, I'd like to assign some jobs... all jobs are at your pace. If you need help or you can't complete/finish a job, let me know...

**Comment by KODeKarnage** [comment]
I recommend using Slack for conversations and Trello for project tasks.

I believe on Trello you can create tasks and either assign them to a person or allow people to pick them up themselves.
