### ISSUE TITLE
PTVL doesn't progress on startup

### ISSUE THREAD

**Issue by undecomposed** [PseudoTV/PseudoTV_Live#22]
Hello!

I have encountered an issue and am wondering what could I do to troubleshoot it.

I have downloaded v.0.2.8e and reset the plugin to start from scratch. However, every time I am entering the settings to configure anything, I get a message background tasks are running and nothing is happening even half an hour later.

I have uploaded the debug log [here](https://paste.kodi.tv/tajesehugu.kodi). What can I do to troubleshoot this?

**Comment by Lunatixz** [comment]
Your log is missing debugging information; pls remember to enable debugging in Kodi prior to encountering any issues. 

All rules that apply to the Kodi forum apply here: I can not / will not support piracy or debug logs with pirate plugins/repos installed... https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons

**Comment by undecomposed** [comment]
Good morning!

I have enabled Kodi's debug logging - PTVL already had debug logging enabled by default - and uploaded the log here: https://paste.kodi.tv/cemozafefu.kodi

I don't believe I have pirate plugins or repos installed, but please let me know if you see any so I can get rid of them.

**Comment by Lunatixz** [comment]
No debugging info in your log: 
_INFO <general>: Disabled debug logging due to GUI setting. Level 0._

Your system still has banned plugins, View the log you sent me, if it has a red plugin name its banned.
