### ISSUE TITLE
Player issues

### ISSUE THREAD

**Issue by RedRaptor10** [PseudoTV/PseudoTV_Live#27]
Continued from my Reddit post:
https://old.reddit.com/r/kodi/comments/n2s0xb/scheduling_shows_in_pseudotv/gxl15fn/

Here are some issues I was having with PseudoTV Live. I want to mention that my video files are playing through Plex (PlexKodiConnect) from a mounted cloud drive (Rclone) so it takes slightly longer to load a video. I am running Kodi Matrix 19.0 and PseudoTV Live version 0.2.9i.

1. Sometimes when playing a channel, it starts at the beginning of the episode instead of the time it's supposed to play at. As you can see, the first time playing a channel, it uses the default Kodi player instead of the channel player. Then the next time I switch to the channel, it works correctly. Perhaps there is a setting I'm missing (either in Kodi or PseudoTV) that's causing this?

_Video:
https://www.youtube.com/watch?v=tqhbzirEoGU
Log:
https://paste.kodi.tv/luwufimusa.kodi_

2. The up/down buttons in the player don't work. In the video you can see me trying to click the Up and Down arrows, which I'm assuming are supposed to switch to a different channels, but they don't do anything. Also for some reason, it's playing the next video in the channel guide _("Bulbasaur... the Ambassador" instead of "A Scare to Remember")_

_Video:
https://www.youtube.com/watch?v=wBQAoS1SpGw
Log:
https://paste.kodi.tv/avehepevij.kodi_

3. After editing an existing channel, I cannot save its settings. After clicking "Save", the loading icon hangs and I am stuck unless I click cancel.

_Video:
https://www.youtube.com/watch?v=aVA2o2AqHww
Log (Part 1):
https://paste.kodi.tv/reqefuhime.kodi
Log (Part 2):
https://paste.kodi.tv/jipejayugo.kodi_

For the 3rd issue, I split the log file because it was too long. There were some more issues I was having, but hopefully getting these resolved will fix the others. Also I apologize if my log files are incorrect (this is my first time posting logs for Kodi).

**Comment by Lunatixz** [comment]
You'll have to post your issue for discussion here:
https://forum.kodi.tv/showthread.php?tid=346803

This isn't considered a bug; PlexKodiConnect is acting as a middleman to Kodi and PseudoTV which is out of the scope of this project. This isn't to say the two can't work together; to my knowledge forums users have figured out how to get the two working... however, I do not use or keep myself updated with Plex/Emby connect projects and have little insight on the topic.

THX

**Comment by RedRaptor10** [comment]
Thanks. I'm not sure why but now the content isn't playing at all. But anyways, I am going to close this issue since it's not a bug and I don't think PseudoTV Live will work for my specific use case. I do look forward to the progress of this add-on and I'll probably use it in the future.

As for the up/down buttons, I don't think it's a problem with PseudoTV Live, but a bug in Kodi since it also happens when I'm not using PseudoTV Live. Not a huge deal since you can use the arrow keys to switch channels. The rename bug is also probably because of my content being connected through PlexKodiConnect, but who knows.
