### ISSUE TITLE
Zap2it, Schedules Direct xmltv support.

### ISSUE THREAD

**Issue by Lunatixz** [PseudoTV/PseudoTV_Live#3]
@learningit @PseudoTV/developers 
I'd like to see if we can incorporate your zap2it site parsing from "US Channels" into PTVL, should be easy... Would be nice if users only have to pass a small string via settings... 
ie. "CAN-0005995-X&zip=M4C%201B5", better if users could enter zip-code info and pull listings directly via config.py

Any data would have to be assembled into a xmltv format, ideally the data would be at least three days worth of listings... in this case we can dump to cache file for reparsing.

PseudoTV Live already uses the xmltv and pyfscache modules.
https://pypi.python.org/pypi/python-xmltv
https://pypi.python.org/pypi/pyfscache/

further discussion can take place here, thanks

**Comment by learningit** [comment]
Zap2it has removed the api that I was using. I have a parser written for http://tv.twcc.com/listings which is similar but doesn't cover the whole country - it's ok for USTVNow. I also have parsers for UK: radiotimes and sky which are ok for FilmOn or NTV. I also have Ireland, Singapore and Japan. Any of them are problematic for random local listings so I wouldn't recommend allowing the user to select zip codes, etc. The twcc listings don't really have Canadian listings either, but I think I saw a source from Rogers that might work.

**Comment by Lunatixz** [comment]
ahhh that sucks zap2it was a good source, How stable is the twc listings? if you believe a source is stable for the long haul then we should go with it... otherwise prob. best to ignore it... don't want to waste anyone's time.

**Comment by learningit** [comment]
It's stable, but limited. It requires a little experimentation to find a source for a given locale. As I remember, it's page oriented (something like 50 entries per page) and you kinda have to screw around requesting pages to find a particular channel. If we have a fixed set of channels from a known locale, it's fine (assuming that locale has a TWC listing). The most disappointing thing is no Canada support, though there are some other places to scrape Canadian channels.

**Comment by Lunatixz** [comment]
Would the end result be simple, User enter zipcode, picks service or channels, and PTVL is able to retrieve the feeds? if yes, would you be able to work on the code for me?

**Comment by learningit** [comment]
With a bunch of caveats, it's doable. It will be quite slow for random channels as up to 30 pages need to be requested to search for a particular channel. As far as I can see, only areas which TWC services are really supported. There are listings for other areas but they tend to be only the local channels.
It's definitely not a universal service. The other issue is that all the listings would need to be normalized to the local timezone. I have some older code which converts to xmltv format so that's the way I'll go for a start. I'll give you something to try in a few days.

**Comment by learningit** [comment]
Still working on this. The filter function on the TWC pages doesn't seem to work consistently, so I need to create a backup method to request and scan through the EPG pages to locate the channel/service I'm looking for. I've created a cache which eases subsequent requests, but may be a space problem for some platforms. The first lookup or a full refresh is a bitch though.
The data on local channels leaves a lot to be desired, there's no program description on most of them and quite often "local programming' is all that's returned.
