### ISSUE TITLE
Type of 'NoneType' has no len()

### ISSUE THREAD

**Issue by jaredkotoff** [PseudoTV/PseudoTV_Live#32]
PseudoTV version: 0.3.1g
PVR IPTV Simple Client: 7.6.9
Kodi version: 19.1.0
Nvidia Shield: Android 9.0.0

This line is throwing an error when PseudoTV is trying to start https://github.com/PseudoTV/PseudoTV_Live/blob/master/plugin.video.pseudotv.live/resources/lib/library.py#L410

`TypeError: object of type 'NoneType' has no len()`

After disabling `Detect compatible Kodi plugins` settings i get this error:
`TypeError: 'NoneType' object is not iterable` on this line: 
https://github.com/PseudoTV/PseudoTV_Live/blob/master/plugin.video.pseudotv.live/resources/lib/library.py#L113

**Comment by Lunatixz** [comment]
Thanks fix will be included with v.0.3.1h
