### ISSUE TITLE
Importing issue

### ISSUE THREAD

**Issue by Spider-netizen** [PseudoTV/PseudoTV_Live#33]
Hi,

I had an issue with importing channels, I believe the problem was with this line:
https://github.com/PseudoTV/PseudoTV_Live/blob/d328f590ccf12a768f3015930e27bc4d2413e042/plugin.video.pseudotv.live/resources/lib/m3u.py#L164

I managed to successfully import the channels once I removed that line.

Thanks for the add-on :]

**Comment by Lunatixz** [comment]
Thanks, Looks like a typo...
