### ISSUE TITLE
Ondemand/Apps menu

### ISSUE THREAD

**Issue by Lunatixz** [PseudoTV/PseudoTV_Live#4]
@KODeKarnage @PseudoTV/developers 

I'd like to start putting together the interface for the ondemand and apps menus. Each have their own *.py and skin *.xml

I envision a container panel 5x2, similar to:
https://twitter.com/PseudoTV_Live/status/604792495315255296, the above was a quick mock up using phil65's extendinfo...

A hidden side menu to the left under the video window would allow users to select from one of four options, ie. New, Popular, Search, user selected smart-playlist

Popular would use trakt data, any non local media would use an internal global search for media via youtube or plugins.

New/User playlist would be easy because most functions exist already. Using pre existing functions and json queries... the format that needs to be interrupted is what I call "tmpstr" it's a m3u format that PTVL uses internally, most functions are written to parse and gather data in this format.
https://github.com/PseudoTV/PseudoTV_Live/blob/master/resources/lib/ChannelList.py#L1133
https://github.com/PseudoTV/PseudoTV_Live/blob/master/resources/lib/ChannelList.py#L5052

Search would use internal global search.

Artwork would be supplied via: https://github.com/PseudoTV/PseudoTV_Live/blob/master/resources/lib/Overlay.py#L2713

further discussion could take place here, i'm weak when it comes to Kodi's gui... I noticed lazyTV has a window very similar to what I want to achieve using functions already written.

**Comment by KODeKarnage** [comment]
Which window?

Have you reached out to any skinners? Can't beat those guys for design.

**Comment by Lunatixz** [comment]
Ondemand.py and apps.py and their matching xmls... I need the framework for a 5x2 container and a function that can fill it... :)

**Comment by tromyl** [comment]
Maybe this could be helpful with search/on demand/find similar stuff...
https://github.com/marcelveldt/script.skin.helper.service
![screenshot049](https://cloud.githubusercontent.com/assets/7497648/10566967/38c8b5a2-75fe-11e5-818d-f869b4217ec9.png)

**Comment by Lunatixz** [comment]
@tromyl looks interesting, I'll take a look... maybe replace the current search feature with this?

**Comment by tromyl** [comment]
Yes,I think it would be better!
