### ISSUE TITLE
PseudoTV does not start next show in non-english languages

### ISSUE THREAD

**Issue by michaelnpsp** [PseudoTV/PseudoTV_Live#40]
**Describe the bug**
Watch any PseudoTV channel in a non-english kodi, wait for the current played show to finish, next show does not start.

**To Reproduce**
1. Goto Interface/Regional settings
2. Change kodi language to spanish or french.
3. Play any PseudoTV channel
4. Wait for the show to finish
5. Black screen with PseudoTV logo and a text message: "Watching: Current Episode Name" is displayed
6. Next episode never starts.

**Expected behavior**
Next epìsode/show should start.

**Desktop (please complete the following information):**
 - Windows 10 profesional
 - Kodi 19.4 Matrix
 - PseudoTV Live 0.3.8
- Tested in two diferent computers including a kodi clean installation.

**Comment by Lunatixz** [comment]
THX I'll look into it.

**Comment by Lunatixz** [comment]
Does this issue persist in v.0.4.0?
