### ISSUE TITLE
Pause when not watching

### ISSUE THREAD

**Issue by HyperSmartian** [PseudoTV/PseudoTV_Live#49]
**Resume from where you left off. Kodi does not have a feature wherein i can resume a playlist from where i leftoff for plugin video sources. Smartplaylists are no go since i want to resume from left off point on youtube playlists and other video addons.**

**Pause and Resume channel when Closing and Opening it Respectively**

**Tried plugging an m3u with youtube links into iptv simple like a vod but doesn't work as intended**

Now i don't know if this exists (nothing about it in forum, no channel rules) in this version but in 'script.pseudotv' theres's an option called 'Pause when not watching'

**Comment by Lunatixz** [comment]
Yes the original project has a resume function because every channel was built as a m3u playlist then queued for playback.

This project though similar in appearance differs greatly in function. I can look into a feature like this down the road, but unfortunately not anytime soon.

Thx

**Comment by HyperSmartian** [comment]
Oh thanks for the effort, all the best to make it seamless!
