### ISSUE TITLE
PseudoTV Live Run button is faded

### ISSUE THREAD

**Issue by mstrauss2018** [PseudoTV/PseudoTV_Live#50]
I have Kodi 19.5 installed.
I am usinf IP TV with pluto and it works fine.
I spent the last 6 hours reading about PseudoTV Live and as far as I can tell it is installed correctly however I cannot run the program or get into configuration in order to set it up.

I tried installing repository.lunatixz-1.0.8, PseudoTV_Live-master and repository.pseudotv-1.0.1 and they all have the same issue.

I have read information about manually setting up files for my local library to work but no details about how to set them up or where.

PLease let me know what I can do to resolve this.

Thanks

I am running Kodi 19.5 on Windows 11

**Comment by Lunatixz** [comment]
Sorry documentation is limited, I suggest you post for help at the PseudoTV sub topic at Kodi.tv forums.

Thx
