### ISSUE TITLE
Unable to update to 0.4.5m as the IPTV dependency is not available

### ISSUE THREAD

**Issue by dshokouhi** [PseudoTV/PseudoTV_Live#51]
**Describe the bug**
Attempt to update PTVL prompts with an update not available message

**To Reproduce**
1. Update add-on to latest version

**Expected behavior**
the add-on should update

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android Nvidia shield
 - Version Kodi 20.3

**Additional context**
not sure what else i need to provide but seems others saw teh same issue in the forums, I guess the new dependency requirement needs Kodi v 21?

https://forum.kodi.tv/showthread.php?tid=376471

**Comment by Lunatixz** [comment]
PseudoTV Live always follows Kodi's master branch. In this case Kodi Omega is required and it's updated IPTV simple.
