### ISSUE TITLE
Skipping channel due to invalid parameters.

### ISSUE THREAD

**Issue by adamj02090830** [PseudoTV/PseudoTV_Live#57]
From v0.5.1t onwards on LibreELEC, I get the error "skipping channel: invalid parameters" after creating channels and during scan. On version 0.5.2 it will not let me select content paths for channels. It also says there are still a few channels in my database after a clean start has been performed. And it won't let me access the node or smartplaylist editors.

**Comment by Lunatixz** [comment]
Channel Manage paths bug was fixed in v.0.5.3.... not sure about "skipping channel" I'd need a debug log.

**Comment by adamj02090830** [comment]
Log says this several times over.

error <general>: UpdateFromScraper: No EPG scraper defined for table ''

**Comment by adamj02090830** [comment]
PseudoTV now says "waiting for pairing" and times out after 60 seconds. After which, still no channels.

**Comment by Lunatixz** [comment]
pairing is for multi-room... you have to configure channels or autotune some...

**Comment by adamj02090830** [comment]
It's still skipping my custom made channels after switching to OSMC.

**Comment by adamj02090830** [comment]
Attached is the debug log.
[kodi.log](https://github.com/user-attachments/files/16804414/kodi.log)

**Comment by Lunatixz** [comment]
THX, log has no debug info, you'll have to enable debugging in both Kodi and the PseudoTV plugin....
I'd suggest posting here for help: https://forum.kodi.tv/forumdisplay.php?fid=231

**Comment by adamj02090830** [comment]
Just posted my issue there last night. I'll put the new log here too, just in case.
[kodi.log](https://github.com/user-attachments/files/16825005/kodi.log)
