### ISSUE TITLE
Hide "Restart" on channel change

### ISSUE THREAD

**Issue by pleg** [PseudoTV/PseudoTV_Live#59]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the "Restart" icon appears on changing channels.

**Describe the solution you'd like**
Provide option to disable the "Restart" appearance

**Describe alternatives you've considered**
There may be a configuration setting i've missed in the Kodi Settings, or directly in the XML

**Additional context**
Option to change how many seconds its displayed, color and position

**Comment by Lunatixz** [comment]
The setting is under "Globals" and was mislabeled as "replay"
