### ISSUE TITLE
Multiroom connects but does nothing.

### ISSUE THREAD

**Issue by loggio** [PseudoTV/PseudoTV_Live#60]
I have server set up on rpi4 with all channels configured and working fine. Server is enabled.

I set up psuedotv on my chromecast in another room, it asks me if I'd like to set up multi room. I select yes and then connect to my pi4.

But after that nothing happens. It doesn't sync with the server or do anything. I had this all working fine but now it's using zero config so not sure why it's not doing anything after choosing a server.

I have deleted addon data, updated to latest addon on both server and client (just now) restarted the server and then set up the client but get exactly same results.

**Comment by Lunatixz** [comment]
Need a debug log, thx

**Comment by loggio** [comment]
Fixed it. After fresh install no channels would show up in the live TV channel list in kodi at all,  despite pseudotv generating the playlist and epg files correctly and configuring iptv settings.

I store the pseudotv playlist, logos and epg files on my smb share qnap server and point on my rpi to that folder as suggested in the pseudotv settings.

Turns out when pseudotv creates settings for the iptv addon, it doesn't like the path to that folder that pseudotv created.

If I manually point iptv to the folder then it works straight away.

Not sure if you've changed something? But this has not been a problem up until now.
