### ISSUE TITLE
Channels show Pseudo TV Live Error or Dissapears

### ISSUE THREAD

**Issue by Semkanu** [PseudoTV/PseudoTV_Live#61]
I have Pseudo TV running on my Raspberry Pi 4 with LibreELEC. A harddrive and a remote control is attached to it. I have 5 different channels with content such as Music Videos(mixed into 45-50min long videos), Cartoon (around 20 minutes episodes), Series, Movies and Sports. I need to run this setup continuously almost 24/7 for a project of mine but Cartoon and Music Videos channels, namely Toon Boom and HTV keeps on failing after a while. The error seem to correct itself after I leave the device running for a day or so but in the meanwhile they either dissapear from the channel select menu or display Pseudo TV Live Error when I choose to play that channel.

Here is the log file that starts when channels were running smoothly and failing after a while. I cant really be sure when they have failed because I only saw this was the case when I opened the display the next day.

Log file: https://paste.kodi.tv/xaqiboyivo

**Comment by Lunatixz** [comment]
Log is missing debugging information.
Version is outdated, current v.0.5.6u

Try reading: https://github.com/PseudoTV/PseudoTV_Live/wiki
If your issues persist, submit proper log... THX
